commandOnSelected: UI: ENH: Allow single-column output via -1|--format=single-column
Like ls -1.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/commandOnSelected b/bin/commandOnSelected
--- a/bin/commandOnSelected
+++ b/bin/commandOnSelected
@@ -18,7 +18,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" "[--accept-single [--auto-selected-entry-message MSG]] [--single-only] [-p|--prompt PROMPT] [--no-entries-message MSG] [--selection-message MSG] [--interactive-selection-message MSG] [-g|--generator GENERATOR] [-f|--filter ''|FILTER] [--post-filter FILTER] [-c|--command \"COMMANDLINE\" [-c ...]] [-?|-h|--help] ..."
+    printf 'Usage: %q %s\n' "$(basename "$1")" "[-1|--format=single-column] [--accept-single [--auto-selected-entry-message MSG]] [--single-only] [-p|--prompt PROMPT] [--no-entries-message MSG] [--selection-message MSG] [--interactive-selection-message MSG] [-g|--generator GENERATOR] [-f|--filter ''|FILTER] [--post-filter FILTER] [-c|--command \"COMMANDLINE\" [-c ...]] [-?|-h|--help] ..."
     echo
     printf 'Usage: %q %s\n' "$(basename "$1")" "... [--] [SELECTION ...] [-- ENTRIES ...]"
     printf 'Usage: %q %s\n' "$(basename "$1")" "... -E|--entries-separated-by ; [ENTRIES ...] ; [--] [SELECTION ...]"
@@ -66,6 +66,9 @@ selections (or allow further filtering of the list via grep, or invert the
 selection via //). The selected entries are then passed to the COMMANDLINE
 (${entriesMarker:+either }appended${entriesMarker:+ or replacing any $entriesMarker marker}) [or printed].
 
+    --format=single-column|-1
+		    List one entry per line instead of the default columnar
+		    format.
     --accept-single Accept a single available ENTRY without prompting the user.
     --single-only   The querying stops when at least one entry has been selected
 		    (and any additional ones are ignored and a warning is
@@ -135,6 +138,7 @@ printIfDefined()
     printf >&2 "${message}\\n" "$@"
 }
 
+isOneEntryPerLine=
 isAcceptSingle=
 isMultiSelect=t
 isStdin=
@@ -154,6 +158,15 @@ while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	    shift; printLongUsage "$0"; exit 0;;
+	--format=single-column|-1)
+			    shift; isOneEntryPerLine=t;;
+	--format)	    shift
+			    case "$1" in
+				single-column) isOneEntryPerLine=t;;
+				*) printf 'ERROR: Unknown format "%s".\n' "$1"; echo; printUsage "$0"; exit 2;;
+			    esac
+			    shift
+			    ;;
 	--accept-single)    shift; isAcceptSingle=t;;
 	--single-only)	    shift; isMultiSelect=;;
 	--stdin)	    shift; isStdin=t;;
@@ -306,6 +319,7 @@ else
     }
     selectCandidates()
     {
+	[ "$isOneEntryPerLine" ] && COLUMNS=1
 	local entry; select entry
 	do
 	    if [ "$entry" ]; then
