commandOnSelected: ENH: Allow passing entries via --entries ; ... ;

diff --git a/bin/commandOnSelected b/bin/commandOnSelected
--- a/bin/commandOnSelected
+++ b/bin/commandOnSelected
@@ -20,10 +20,12 @@ printShortUsage()
     printf 'Usage: %q %s\n' "$(basename "$1")" "[--accept-single [--auto-selected-entry-message MSG]] [--single-only] [-p|--prompt PROMPT] [--no-entries-message MSG] [--selection-message MSG|--interactive-selection-message MSG] [-g|--generator GENERATOR] [-f|--filter ''|FILTER] [--post-filter FILTER] [-c|--command \"COMMANDLINE\" [-c ...]] [-?|-h|--help] ..."
     echo
     printf 'Usage: %q %s\n' "$(basename "$1")" "... [--] [SELECTION ...] [--] [ENTRIES ...]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "... --entries ; [ENTRIES ...] ; [--] [SELECTION ...]"
     echo
     printf 'Usage: %q %s\n' "$(basename "$1")" "... --allow-literal-match|--allow-glob-match [--] [MATCH ...|SELECTION ...] -- [ENTRIES ...]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "... --allow-literal-match|--allow-glob-match --entries ; [ENTRIES ...] ; [--] [MATCH ...|SELECTION ...]"
     echo
-    printf 'Usage: GENERATOR | %q %s\n' "$(basename "$1")" '... --stdin [-c ...]'
+    printf 'Usage: GENERATOR | %q %s\n' "$(basename "$1")" '... [--entries ; [ENTRIES ...] ;] --stdin [-c ...]'
 }
 printUsage()
 {
@@ -101,7 +103,12 @@ replacing any $entriesMarker marker}) [or printed].
 		    an (anchored, extended) glob MATCH is selected. Multiple
 		    arguments must be all MATCHes or all SELECTIONs; mixing is
 		    not allowed.
-
+    --entries ; [ENTRIES ...] ;
+		    Any arguments between ; and ; (or any other separator) as
+		    entries. This alternative form allows to pass SELECTIONs at
+		    the end and prevents the user from sneaking in additional
+		    ENTRIES via "SELECTION -- ENTRY", and therefore is the
+		    preferred form and especially useful for shell aliases.
 EXIT STATUS
 Exits with 2 if a bad selection was made, 124 if there are no entries available,
 125 if no entries were selected.
@@ -127,6 +134,7 @@ noEntriesMessage=
 autoSelectedEntryMessage=
 selectionMessage=
 interactiveSelectionMessage=
+typeset -a entries=()
 while [ $# -ne 0 ]
 do
     case "$1" in
@@ -150,6 +158,21 @@ do
 			    shift; selectionMessage="$1"; shift;;
 	--interactive-selection-message)
 			    shift; interactiveSelectionMessage="$1"; shift;;
+	--entries|-e)	    shift
+			    sep="${1:?}"; shift
+			    until [ "$1" = "$sep" ]
+			    do
+				if [ $# -eq 0 ]; then
+				    printf 'ERROR: Missing concluding "%s" after "%s" separator.\n' "$sep" '--entries|-e'
+				    echo
+				    printUsage "$0"
+				    exit 2
+				fi >&2
+
+				entries+=("$1"); shift
+			    done
+			    shift
+			    ;;
 	--)		    shift; break;;
 	-[^0-9]*)	    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
 	*)		    break;
@@ -192,11 +215,10 @@ if [ ${#selected[@]} -gt 0 -a ${#matches[@]} -gt 0 ]; then
     exit 2
 fi >&2
 
-typeset -a entries=()
-if [ $# -gt 0 ]; then
+if [ ${#entries[@]} -eq 0 -a $# -gt 0 ]; then	# Ignore stuff after -- if --entries have been used.
     entries=("$@")
 elif [ "$isStdin" ]; then
-    readarray -t entries
+    readarray -O ${#entries[@]} -t entries  # Append to entries supplied via --entries.
     { exec 0</dev/tty; } 2>/dev/null || exit $?
 fi
 
