Tests: Complete test coverage
System-info: Ubuntu 24.04.3 LTS, x86_64
Platform-info: bash 5.2.21(1)-release, Bats 1.10.0

diff --git a/bin/dishOutSections b/bin/dishOutSections
--- a/bin/dishOutSections
+++ b/bin/dishOutSections
@@ -98,7 +98,9 @@ do
 done
 [ "$isReset" ] && databaseAction=reset
 if [ $# -ne 1 ]; then
-    echo 'ERROR: No FILE passed.'
+    [ $# -eq 0 ] \
+	&& echo 'ERROR: No FILE passed.' \
+	|| echo 'ERROR: Need one FILE.'
     echo
     printUsage "$0"
     exit 2
