Refactoring: Parsing of multiple command-line arguments

diff --git a/bin/makeScript b/bin/makeScript
--- a/bin/makeScript
+++ b/bin/makeScript
@@ -12,11 +12,16 @@ HELPTEXT
 
 isSudo=
 SUDO=
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --sudo)		shift; isSudo=t;;
-    --)			shift;;
-esac
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	    shift; printUsage "$0"; exit 0;;
+	--sudo)		    shift; isSudo=t;;
+	--)		    shift; break;;
+	-*)		    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		    break;;
+    esac
+done
 if [ $# -ne 1 ]; then
     printUsage "$0" >&2
     exit 2
