CHG: Replace optional -f|--file on the template parameter with optional -t|--target on the target parameter
Though it's modeled after "sed -f script-file" and "awk -f program-file" and allows for nice invocation options, the difference is that sed and awk can be found in default locations and therefore can be specified via absolute path in the shebang, whereas for this personal script, the absolute path is very long (and possibly different due to the flexible home directory location). The only way out would be a symlink in /usr/local/bin (error prone and also not 100% stable as an absolute location, as it's just a convention). It's much better to rely on a PATH lookup via /usr/bin/env, but then the command itself becomes the single parsed argument, and the default "-f" argument cannot be specified. (Unless we start relying on new GNU coreutils 8.30 (from 2018, so not even in Ubuntu 16.04)'s new -S option.)
So, let's turn this around, and replace the marking of the template file parameter with an optional marking of the target file. As the embedding of the target file now would take two arguments (-t and TARGET_FILE), also allow the short -tTARGET_FILE and --target=TARGET_FILE parsing variants, if users really want to embed the target file while not using env -S and instead supplying the absolute path. All of that is highly unlikely (but nice to offer, which is why I initially went that route). The benefit of the new solution is that the (easily forgotten) -f is not necessary any longer.

diff --git a/bin/shelltemplate b/bin/shelltemplate
--- a/bin/shelltemplate
+++ b/bin/shelltemplate
@@ -10,23 +10,52 @@ the result / write the result to TARGET-FILE. Backslashes must be doubled; all
 other characters can remain as-is, like in a double-quoted string in the shell.
 HELPTEXT
     echo
-    printf 'Usage: [VAR=... [...]] %q %s\n' "$(basename "$1")" '-f|--file TEMPLATE-FILE [TARGET-FILE]'
-    printf 'Usage: [VAR=... [...]] %q %s\n' "$(basename "$1")" '[--] TARGET-FILE TEMPLATE-FILE'
+    printf 'Usage: [VAR=... [...]] %q %s\n' "$(basename "$1")" '[--] TEMPLATE-FILE [TARGET-FILE]'
+    printf 'Usage: [VAR=... [...]] %q %s\n' "$(basename "$1")" '-t|--target TARGET-FILE [--] TEMPLATE-FILE'
     echo
     cat <<HELPSHEBANG
 This can be used as a simple template expander where the template file uses a
 shebang to evaluate itself:
 HELPSHEBANG
-    printf '#!%q %s\nTEMPLATE-TEXT\n...\n' "$(basename "$1")" '-f|--file|TARGET-FILE'
-    printf 'Usage: TEMPLATE-FILE %s\n' '[TARGET-FILE]'
+    printf '#!/usr/bin/env %q\nTEMPLATE-TEXT\n...\n' "$(basename "$1")"
+    printf 'Usage: TEMPLATE-FILE %s\n' '[[-t|--target] TARGET-FILE]'
 }
 
-templateFile=
-case "$1" in
-    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
-    --file|-f)		shift; templateFile="$1"; shift;;
-    --)			shift;;
-esac
+templateFilespec=
+targetFilespec=
+while [ $# -ne 0 ]
+do
+    case "$1" in
+	--help|-h|-\?)	    shift; printUsage "$0"; exit 0;;
+	--target|-t)	    shift; targetFilespec="$1"; shift;;
+	--target=*)	    targetFilespec="${1#--target=}"; shift;;
+	-t*)		    targetFilespec="${1#-t}"; shift;;
+	--)		    shift
+			    if [ -z "$templateFilespec" ] && [ $# -gt 0 ]; then
+				templateFilespec="$1"; shift
+			    fi
+			    break
+			    ;;
+	-*)		    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	*)		    if [ -z "$templateFilespec" ]; then
+				templateFilespec="$1"; shift
+				# Do not break yet to allow a -t|--target
+				# _after_ the TEMPLATE-FILE for the shebang with
+				# user passing the -t use case.
+			    else
+				break
+			    fi
+			    ;;
+    esac
+done
+if [ $# -eq 0 ]; then
+    :
+elif [ $# -eq 1 -a -z "$targetFilespec" ]; then
+    targetFilespec="$1"; shift
+else
+    printUsage "$0" >&2
+    exit 2
+fi
 
 printEvaluatedTemplateWithoutShebang()
 {
@@ -39,18 +68,4 @@ evalTemplate()
     eval 'printEvaluatedTemplateWithoutShebang "${1:?}"' ${2:+'> "$2"'}
 }
 
-if [ -n "$templateFile" ]; then
-    case $# in
-	0) evalTemplate "$templateFile";;
-	1) evalTemplate "$templateFile" "$1";;
-	*)  printUsage "$0" >&2
-	    exit 2
-	    ;;
-    esac
-else
-    if [ $# -ne 2 ]; then
-	printUsage "$0" >&2
-	exit 2
-    fi
-    evalTemplate "$2" "$1"
-fi
+evalTemplate "$templateFilespec" "$targetFilespec"
