Sequential execution requires buffering
A complex scheme with signals or a file counter could orchestrate the individual commands in the pipeline of tees, but the pipes can only buffer so much; I guess it would still block or abort if there's too much input data. Just disallow this combination.

diff --git a/bin/ytee b/bin/ytee
--- a/bin/ytee
+++ b/bin/ytee
@@ -124,7 +124,8 @@ case "$buffering" in
 	    commandLines=("${commandLines[@]/%/; \} >&3 ) |}")
 	    eval "${commandLines[@]}" "{ $lastCommandLine; } >&3" 3>&1
 	else
-	    :
+	    echo >&2 'ERROR: Sequential execution is only possible with buffering; pass -i|--input-buffered or -o|--output-buffered.'
+	    exit 2
 	fi
 	;;
     *)
